# Language tooling for Rust, C/C++, JS/TS, Lua, and Quickshell's QML, plus
# the wallust-driven color theme. Extensions are the store-managed,
# `mutableExtensionsDir = true` default (home-manager's own default when no
# extra profiles are declared) — Nix pins their versions, but the extensions
# marketplace/CLI can still install more on top, same "declarative core,
# mutable on top" spirit as everything else here.
#
# Theming follows the mako/btop split (see wallust.nix, docs/theming.md):
# structural bits (this file, Nix-managed) vs. color values (a file outside
# the Nix store that wallust owns outright). VS Code has neither an
# `include`-style mechanism nor live theme reload, so the split takes the
# shape of an unpackaged "wallust-theme" extension: home-manager writes its
# static `package.json` manifest below (never changes, safe to be a
# read-only store symlink), while wallust.nix's [templates.vscode] renders
# the actual color values straight into that extension's
# themes/wallust-color-theme.json, outside home-manager's management, on
# every `wallust run`. See docs/vscode.md for the full writeup and the one
# manual step (`Developer: Reload Window`) this still requires.
{ pkgs, ... }:
{
  programs.vscode = {
    enable = true;
    package = pkgs.vscode;

    profiles.default = {
      extensions = with pkgs.vscode-extensions; [
        rust-lang.rust-analyzer
        llvm-vs-code-extensions.vscode-clangd
        jnoortheen.nix-ide
        sumneko.lua
        dbaeumer.vscode-eslint
        esbenp.prettier-vscode
      ] ++ [
        # Not in nixpkgs's curated extension set — fetched straight from the
        # marketplace and pinned by hash like anything else in this repo.
        # cutetee.qml is plain syntax highlighting/snippets, not a full
        # language server: qmlls/qmlformat already live in neovim.nix via
        # qt6.qtdeclarative for actual Quickshell QML editing, so this is
        # just parity for whichever editor you happen to have a file open
        # in (see docs/quickshell/README.md's "learning, not delivery" note
        # — this repo doesn't try to build you a full QML IDE either).
        (pkgs.vscode-utils.buildVscodeMarketplaceExtension {
          mktplcRef = {
            name = "qml";
            publisher = "cutetee";
            version = "1.1.0";
            hash = "sha256-qxnrFPZTFq4b0r2uYkJvy0L1mJ4gPcLc0VQBiIF7JW0=";
          };
        })
      ];

      userSettings = {
        "workbench.colorTheme" = "Wallust";
        "editor.fontFamily" = "'JetBrainsMono Nerd Font', monospace";

        # No format-on-save here either — same reasoning as neovim.nix's
        # conform.nvim setup: an unfamiliar formatter silently rewriting a
        # buffer on every save is more surprising than helpful. Format
        # on-demand (Shift+Alt+F) still works via each extension below.
        "editor.formatOnSave" = false;

        "rust-analyzer.check.command" = "clippy";
        "[nix]"."editor.tabSize" = 2;
      };
    };
  };

  # clangd (for the extension above) and a working Rust toolchain (rust-
  # analyzer's extension bundles its own server binary, but — same gotcha
  # documented in neovim.nix — it shells out to `cargo`/`rustc` for
  # sysroot/workspace resolution and hard-errors without them on PATH).
  # lua-language-server likewise for the Lua extension.
  home.packages = with pkgs; [
    clang-tools
    cargo
    rustc
    lua-language-server
  ];

  # The extension manifest itself — static, so a home-manager-managed
  # (read-only) symlink is fine. Only the sibling themes/*.json file is
  # left for wallust to own as a plain mutable file; see wallust.nix.
  home.file.".vscode/extensions/wallust-theme/package.json".text = builtins.toJSON {
    name = "wallust-theme";
    displayName = "Wallust Theme";
    description = "Wallpaper-reactive color theme generated by wallust";
    version = "0.0.1";
    publisher = "local";
    engines.vscode = "^1.70.0";
    categories = [ "Themes" ];
    contributes.themes = [
      {
        label = "Wallust";
        uiTheme = "vs-dark";
        path = "./themes/wallust-color-theme.json";
      }
    ];
  };
}
